### ISSUE TITLE
release latest version

### ISSUE THREAD

**Issue by harelwa** [conda-forge/superset-feedstock#9]
Issue:
- `superset` has joined the Apache SW Foundation [ ref [official new website](https://superset.apache.org/) ]
- It is now called [ in pypi ] `apache-superset`
- Latest release of `apache-superset` in 0.37.1, Sep 15th, 2020 [ ref [apache-superset @ pypi ](https://pypi.org/project/apache-superset/) ]
- can you pls consider deploying `apache-superset` latest ? 
  I hope to save the trouble of a new recipe, or perhaps fork this one and adjust accordingly ?

Thank you,
Harel
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mariusvniekerk** [comment]
Done in #10
